spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          ignore-local-ssh-settings: true
          host-key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCcwnYnAWYGbv3IxfDjrUthcnwuHQ83CO/cxBZplxrLrBN1UEmroy73uKBkrCEblmAESXKH7hx2ztGH7LNsCFtetS/c1nIe0N8iUpi4bW8pQ3awYvElM8GJe903r/+r0tKk95l9EOz1YadPAtGncOUINqK3JG5Q1kdPEZ2kKYp/Gu8dBp3bSv1ZTie/hfhWqp5AYQxA+J4FCjtEOpLl3xd6nHVrzVZ8wwNaD8aBvJf+WY2/fi7h0yVC0QtZ4lcXOnWb4Y/mMXLrj+bcLS36Ge4RGGAJJvWkZbTlFbfppCKCZUD1/WAWcGWy+XZwCJUOZIOeHP106/zIB+HTX/IDZlPL
          private-key: | # Add the config service key below
                        PEM FORMAT

          uri: ssh://git@github.com:metron2/spring-config-server.git # Replace with your URI
  security:
    user:
      name: config
      password: config
